apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: c4c-extension-with-user-context
  name: c4c-extension-with-user-context
spec:
  replicas: 1
  selector:
    matchLabels:
      app: c4c-extension-with-user-context
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: c4c-extension-with-user-context
    spec:
      containers:
      - image: jcawley5/c4c-extension-with-user-context:latest
        name: c4c-extension-with-user-context
        resources: {}
        ports:
          - containerPort: 8080
        env:
          - name: DESTINATION_OAUTH_TOKEN_URL
            value: $(url)/oauth/token
          - name: DESTINATION_OAUTH_CLIENT_ID
            value: $(clientid)
          - name: DESTINATION_OAUTH_CLIENT_SECRET
            value: $(clientsecret)
          - name: DESTINATION_URL
            value: $(uri)/destination-configuration/v1/destinations
          - name: DESTINATION_NAME
            value: {provide name of destinaton created in SAP BTP} #should be updated
status: {}
---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: c4c-extension-with-user-context
  name: c4c-extension-with-user-context
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: c4c-extension-with-user-context
status:
  loadBalancer: {}
