apiVersion: telemetry.kyma-project.io/v1alpha1
kind: LogPipeline
metadata:
  name: my-cls-application-logs
  namespace: cls
spec:
  input:
    application:
      containers:
        exclude:
          - istio-proxy
  output:
    http:
      dedot: true
      host:
        valueFrom:
          secretKeyRef:
            name: my-cls-binding
            namespace: cls
            key: ingest-mtls-endpoint
      tls:
        cert:
          valueFrom:
            secretKeyRef:
              name: my-cls-binding
              namespace: cls
              key: ingest-mtls-cert
        key:
          valueFrom:
            secretKeyRef:
              name: my-cls-binding
              namespace: cls
              key: ingest-mtls-key
      uri: /customindex/kyma
