apiVersion: eventing.knative.dev/v1alpha1
kind: Trigger
metadata:
  name: api-mssql-go-trigger
spec:
  broker: default
  filter:
    attributes:
      eventtypeversion: v1
      source: mp-commerce-mock # name of the application/system
      type: order.created # event type
  subscriber:
    ref:
      apiVersion: v1
      kind: Service
      name: api-mssql-go
      namespace: dev
    uri: /orderCodeEvent
