apiVersion: serverless.kyma-project.io/v1alpha1
kind: Function
metadata:
  name: api-mssql-function
  labels:
    app: api-mssql-function
    app.kubernetes.io/managed-by: Helm
spec:
  env:
    - name: database
      value: BotKnowledgeDB
    - name: host
      value: mssql.chatbot.svc.cluster.local    #change chatbot to your namespace
    - name: password
      value: mfrCPTK3
    - name: username
      value: sa
  type: git
  runtime: nodejs14
  source: github-repo
  reference: main
  baseDir: chatbot-conversational_AI/knowledge-database/api-mssql-function/function
---
apiVersion: gateway.kyma-project.io/v1alpha1
kind: APIRule
metadata:
  name: api-mssql-function
  labels:
    app.kubernetes.io/managed-by: Helm
spec:
  gateway: kyma-gateway.kyma-system.svc.cluster.local
  rules:
    - path: /.*
      accessStrategies:
        - config: {}
          handler: noop
      methods:
        - GET
        - POST
        - DELETE
  service:
    host: api-mssql-function
    name: api-mssql-function
    port: 80
