apiVersion: v1
kind: Secret
metadata:
  name: bot-secret
  labels:
    app: bot-secret
    app.kubernetes.io/managed-by: Helm
type: Opaque
stringData:
  cai-credentials-url: https://sapcai-community.authentication.eu10.hana.ondemand.com/oauth/token
  cai-credentials-id: xxxxxxxxx
  cai-credentials-secret: xxxxxxxxx
  #bot-url: https://api.cai.tools.sap/train/v2/users/{user_slug}/bots/{bot_slug}/versions/{version_slug}/qna/topic/knowledge_sources/{knowledge_source_id}/answers
  bot-url:  https://api.cai.tools.sap/train/v2/users/xxxxxxxxxxx/bots/xxxxxxxxxx/versions/xxxxxxxxxxxxxx/qna/topic/knowledge_sources/xxxxxxxxxxxxxxxxxxxxx/answers
  cai-x-token: xxxxxxxxx
  stack-url: https://sap.stackenterprise.co/api/2.2
  stack-tag: kyma-runtime
  stack-key: xxxxxxxxx
  db-name: BotKnowledgeDB
  db-host: mssql.chatbot.svc.cluster.local
  db-username: sa
  db-password: mfrCPTK3
