apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: kyma-identity-propagation-spa
  name: kyma-identity-propagation-spa
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kyma-identity-propagation-spa
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: kyma-identity-propagation-spa
    spec:
      containers:
      - image: jcawley5/kyma-identity-propagation-spa:latest
        imagePullPolicy: Always
        name: kyma-identity-propagation-spa
        resources: {}
        ports:
        - containerPort: 80
status: {}
---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: kyma-identity-propagation-spa
  name: kyma-identity-propagation-spa
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: kyma-identity-propagation-spa
status:
  loadBalancer: {}
