# Default values for cap-orders-service.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: {your-docker-account}/cap-orders-service
  pullPolicy: Always
  # Overrides the image tag whose default is the chart appVersion.
  tag: "latest"

vcapsecret:
  name: orders-vcap-services

nameOverride: "cap-orders-service"
fullnameOverride: "cap-orders-service"

service:
  port: 4004
  targetPort: 4004

cc:
  proxyhost: ""
  proxyport: 20003

mockhost: "http://order-mock.cap.svc.cluster.local:80"
alertnotifsrv: "http://alert-notif.cap.svc.cluster.local"
